# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b943f3942446ebd9ec24bd0b80d2520a71cd59507f10cc91e27c4244aab015b0cf53d744f3d296ce846cbfff25d43aab551eccb4a09e37a736e01b04d0717194

test:
  secret_key_base: 4e2fd802d9c9aad6b35c62d46d60b9e6d2b6c038247405894a08127d203dc904e87151bddaaaa3a23107ae4a65f6d9a4dfe63cafb94ea6b308550648ae352c99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
